name: 'Delete image tag from Registry'
description: 'Delete image tag from Registry, for now rename it to outdated'
inputs:
  namespace:
    description: 'Namespace'
    required: true
  scw_access_key:
    description: 'scw_access_key'
    required: true
  scw_secret_key:
    description: 'scw_secret_key'
    required: true
  scw_default_project_id:
    description: 'scw_default_project_id'
    required: true
  scw_default_organization_id:
    description: 'scw_default_organization_id'
    required: true
  image_name:
    description: 'Image name'
    required: true
  tag:
    description: 'Image tags'
    required: true

runs:
  using: "composite"
  steps:
    - name: Clean tag
      uses: OpenSourcePolitics/clean-tag-action@master
      id: clean_tag
      with:
        tag: ${{ inputs.tag }}
    - name: Use CLI
      uses: scaleway/action-scw@v0
      with:
        save_config: true
        export_config: true
        version: v2.13.0
        access-key: ${{ inputs.scw_access_key }}
        secret-key: ${{ inputs.scw_secret_key }}
        default-project-id: ${{ inputs.scw_default_project_id }}
        default-organization-id: ${{ secrets.scw_default_organization_id }}
    - name: Get namespace list
      uses: scaleway/action-scw@v0
      id: namespace_list
      with:
        args: scw registry namespace list name=${{ input.namespace }} -o json
    - name: Get namespace id
      shell: bash
      id: namespace_id
      run: |
        echo "::set-output name=id::$(echo '${{ steps.namespace_list.outputs.stdout }}' | jq -r '.[0].id')"
    - name: Get image list
      uses: scaleway/action-scw@v0
      id: image_list
      with:
          args: scw registry image list namespace-id=${{ steps.namespace_id.outputs.id }} name=${{ input.image_name }} -o json
    - name: Get image id
      shell: bash
      id: image_id
      run: |
          echo "::set-output name=id::$(echo '${{ steps.image_list.outputs.stdout }}' | jq -r '.[0].id')"
    - name: Get tag list
      uses: scaleway/action-scw@v0
      id: tag_list
      with:
          args: scw registry tag list image-id=${{ steps.image_id.outputs.id }} -name=${{ steps.clean_tag.outputs.tag }} -o json
    - name: Get tag id
      shell: bash
      id: tag_id
      run: |
          echo "::set-output name=id::$(echo '${{ steps.tag_list.outputs.stdout }}' | jq -r '.[0].id')"
    - name: Delete tag
      uses: scaleway/action-scw@v0
      with:
          args: scw registry image tag delete ${{ steps.tag_id.outputs.id }}
